{
   "apiVersion": "v2",
   "dependencies": [
      {
         "name": "argo-cd",
         "repository": "https://argoproj.github.io/argo-helm",
         "version": "4.10.0"
      }
   ],
   "name": "argo-cd",
   "version": "4.10.0"
}
